GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/60d8eb3d25c53b159c62a6bb

###
GET http://localhost:3001/info

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Albert Einstein",
    "number": "321-391-23128"
}

###
DELETE http://localhost:3001/api/persons/60da46b5dd3c1f22309b643f